### ISSUE TITLE
capitalize=True and numerals=True lead to IndexError

### ISSUE THREAD

**Issue by berezovskyi** [vinces1979/pwgen#5]
After running `pwgen.pwgen(capitalize=True,numerals=True,symbols=True,no_ambiguous=True)` for a number of times, I repeatedly get

```
>>> pwgen.pwgen(capitalize=True,numerals=True,symbols=True,no_ambiguous=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Python27\lib\site-packages\pwgen\__init__.py", line 72, in pwgen
    passwd = replaceRandomChar(choice(Digits), passwd)
  File "c:\Python27\lib\site-packages\pwgen\__init__.py", line 33, in replaceRan
domChar
    word[pos] = letter
IndexError: list assignment index out of range
```

Issue persists when `numerals=True` is removed:

```
>>> [pwgen(capitalize=True,symbols=True,no_ambiguous=True) for x in range(500)]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Python27\lib\site-packages\pwgen\__init__.py", line 70, in pwgen
    passwd = replaceRandomChar(choice(UpperCase), passwd)
  File "c:\Python27\lib\site-packages\pwgen\__init__.py", line 33, in replaceRan
domChar
    word[pos] = letter
IndexError: list assignment index out of range
```

Python version 2.7.5 on Windows 8.1 x64
pwgen version: 0.4

**Comment by vinces1979** [comment]
fixed
